# toolbar:
#   - styleselect | bold italic | bullist numlist outdent indent | undo redo | image link
#   - fontsizeselect | alignleft aligncenter alignright | forecolor backcolor | table
# fontsize_formats:
#   - 8pt 10pt 12pt 14pt 18pt 24pt 36pt
# plugins:
#   - image
#   - link
#   - textcolor
#   - table

default:
  menubar: false
  statusbar: false
  plugins: 
    - advlist autolink lists link image charmap print preview anchor textcolor searchreplace visualblocks fullscreen 
    - insertdatetime media contextmenu paste code wordcount
  toolbar: 
    - undo redo | bold italic forecolor backcolor  | alignleft aligncenter alignright alignjustify
  content_css: '/assets/tinymce.css'
  
extended:
  menubar: false
  statusbar: false
  plugins: 
    - advlist autolink lists link image charmap print preview anchor textcolor searchreplace visualblocks fullscreen 
    - insertdatetime media table contextmenu paste code wordcount
  toolbar: 
    - insert | undo redo |  formatselect | bold italic forecolor backcolor  | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | table | removeformat
  insert_toolbar: quickimage quicktable
  content_css: '/assets/tinymce.css'
